apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: oranje-markt
type: Opaque
stringData:
  POSTGRES_USER: oranje
  POSTGRES_PASSWORD: oranje123
  POSTGRES_DB: oranjedb
  DATABASE_URL: "postgresql://oranje:oranje123@postgres:5432/oranjedb?schema=public"
