apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: oranje-markt
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator
          image: kadchaosteam3acr.azurecr.io/oranje-markt-traffic-generator:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: traffic-generator-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      terminationGracePeriodSeconds: 60
